<?php

use Fisharebest\Webtrees\View;
use Fisharebest\Webtrees\Services\ModuleService;
use Fisharebest\Webtrees\Module\ModuleThemeInterface;
use Fisharebest\Webtrees\Module\ModuleGlobalInterface;

?>

<?php foreach (app(ModuleThemeInterface::class)->stylesheets() as $stylesheet) : ?>
    <link rel="stylesheet" href="<?= e($stylesheet) ?>">
<?php endforeach ?>

<?= View::stack('styles') ?>

<?= app(ModuleService::class)->findByInterface(ModuleGlobalInterface::class)->map(static function (ModuleGlobalInterface $module): string {
    return $module->headContent();
})->implode('') ?>
