<?php

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Http\RequestHandlers\SearchQuickAction;

?>

<div class="col wt-header-search">
    <form method="post" action="<?= e(route(SearchQuickAction::class, ['tree' => $tree->name()])) ?>" class="wt-header-search-form" role="search">
        <?= csrf_field() ?>
        <div class="input-group">
            <label class="sr-only" for="quick-search"><?= I18N::translate('Search') ?></label>
            <input type="search" class="form-control wt-header-search-field" id="quick-search" name="query" size="15" placeholder="<?= I18N::translate('Search') ?>">
            <div class="input-group-append">
                <button type="submit" class="btn btn-primary wt-header-search-button">
                    <?= view('icons/search') ?>
                </button>
            </div>
        </div>
    </form>
</div>
