<?php use Fisharebest\Webtrees\View; ?>

<?php View::push('javascript') ?>
<script>
    // Bootstrap active tab in navbar
    var url = location.href;
    $('.wt-primary-navigation').find('a[href="' + url + '"]').addClass('active').parents('li').find('.nav-link').addClass('jc-nav-link-active');
    $('.wt-secondary-navigation').find('a[href="' + url + '"]').addClass('active');

    // Individual page main image - add classes for styling purposes
    $('.wt-route-IndividualPage').find('.col-sm-8 > .row > .col-sm-3').addClass('jc-indi-header-image-container')
        .find('a[href*="add-fact"]').addClass('jc-icon-add').parent('div').addClass('mt-2').removeClass('text-center');
    $('.wt-individual-silhouette').parent('.img-thumbnail').addClass('jc-indi-silhouette-container');

    // Remove class from caption (this class cannot be overwritten with css)
    $('caption').removeClass('text-center');

    // Descendants chart - add classes for styling purposes
    $('.wt-chart-descendants [id^="fam"]').each(function () {
        $(this).addClass('jc-chart-descendants-family'),
            $(this).find('.wt-chart-box:first').addClass('jc-chart-box-parent'),
            $(this).find('.d-flex:first').find('.wt-chart-vertical-indent:first').addClass('jc-chart-first-indent')
    });

    // Ancestors chart - add classes for styling purposes
    $('.wt-chart-ancestors [id^="fam"]').each(function () {
        $(this)
            .find('.d-flex:first')
            .addClass('mb-2')
            .next('.d-flex')
            .find('.wt-chart-vertical-indent')
            .addClass('jc-chart-first-indent')
    });

    // General indentation - only indent elements when preceded by a collapse icon
    $('.indent').parents('.collapse').find('.indent').addClass('jc-indent-collapse');

     // Notes treatment
    $('.fact_NOTE').each(function(){

        var $this = $(this);

        // Special treatment for note facts. The do not have a indent class while they are preceded by a collapse icon
        var $collapse = $this.next('.collapse');
        $collapse.addClass('indent jc-indent-collapse');

        // Give the single note-title a class to work with
        var $title = $this.contents().not($this.children());
        if ($title.text().length > 1) {
            $title.wrap('<span class="note-title">');
        }

        // Give the shared note-title a class to work with
        var $title = $this.find('.label').next('a').find('span');
        if ($title.text().length > 1) {
            $title.addClass('note-title');
        }

        // Toggle the title to expand when the full text is collapsed and vice versa
        $title = $this.find('.note-title');

        if ($collapse.hasClass('show')) {
            $title.addClass('collapse');
        } else {
            $title.addClass('collapse show');
        }

        $this.find('.wt-icon-expand').on('click', function() {
            $title.removeClass('show');
        });
        $this.find('.wt-icon-collapse').on('click', function() {
            $title.addClass('show');
        });
    });

    // Individual page Facts Tab, Name Card / Family page - restyle gallery caption
    $('.wt-tab-facts, .wt-route-FamilyPage .wt-facts-table, #individual-names .card-body')
        .find('.gallery').parents('.d-flex').each(function() {
            $(this).addClass('flex-column').removeClass('align-items-center');
            $(this).children('div').eq(1).find('a:first').addClass('jc-gallery-caption');
        });

    // Individual page Stories Tab
    $('.wt-tab-stories .story_title').addClass('h3 text-left').removeClass('text-center');

    // Individual page Facts Tab add fact button / paste fact button
    // See add-fact-row.phtml en paste-fact-row.phtml
    // Replace btn-light for btn-secondary class. This fits better in our palettes.
    $('.input-group-append .btn-light').addClass('btn-secondary').removeClass('btn-light');

    // Markdown table style
    $('.markdown table').each(function () {
        $(this).addClass('table table-sm table-responsive jc-markdown-table');
        $(this).find('tbody').prepend('<tr><td  class="jc-markdown-table-separator" colspan="' + jQuery(this).find("th").length + '"></tr>');
    });

    // Blocks: Changes block
    $('.wt-table-changes').addClass('table-bordered table-striped');

    // Blocks: Journal block (wt-block-gedcom_news / wt-block-user_blog)
    $('.wt-block-content-gedcom_news, .wt-block-content-user_blog')
        .find('p .btn-link').addClass('jc-icon-add').end()
        .find('.news_box').addClass('mb-3')
        .find('.news_title').addClass('h4').end()
        .find('.news_date').addClass('small mb-2').end()
        .find('hr').addClass('my-0').end()
        .find('a.btn-link').addClass('jc-icon-edit').end()
        .find('button.btn-link').addClass('jc-icon-delete').end()
        .find('form').addClass('text-right');

    // Badges static page - maybe we should restyle all badges
    $('.wt-statistics-chart').find('.badge-secondary').addClass('badge-dark').removeClass('badge-pill', 'badge-secondary');

    // Icons - Use fontawesome. These icons do not have a view to alter
    $('.icon-indis').addClass('fas fa-user');
    $('.icon-mypage').addClass('fas fa-tachometer-alt');
    $('.icon-selected').addClass('fas fa-check');
    $('.wt-icon-add').parent('.btn').removeClass('btn-secondary').addClass('jc-btn-secondary');
    $('.wt-icon-preferences').parent('.btn-link').addClass('ml-n1');

    // Prevent underlining when hovering over icons
    $('[class*="icon-"]').closest('a').addClass('text-decoration-none');

    // Use the default bootstrap badge class for the odometer
    $('.jc-palette-justlight').find('.odometer').addClass('badge badge-dark');
    $('.jc-palette-justblack').find('.odometer').addClass('badge badge-light');

    // Place the cookie warning after the footer. The cookie warning is part of the privacy-policy footer
    $('footer').after($('#cookie-warning'));
    $('#cookie-warning').addClass('jc-cookie-warning mt-n2');

</script>
<?php View::endpush() ?>
