<?php /** JustLight Theme - Load theme font - See: https://icomoon.io/ */ ?>

@font-face {
  font-family: 'icomoon';
  src: url("<?= $eot_url ?>");
  src: url("<?= $eot_url ?>#iefix") format("embedded-opentype"), 
    url("<?= $ttf_url ?>") format("truetype"), 
    url("<?= $woff_url ?>") format("woff"), 
    url("<?= $svg_url ?>#icomoon") format("svg");
  font-weight: normal;
  font-style: normal;
  font-display: block;
}
