<?php

use Fisharebest\Webtrees\Http\RequestHandlers\MessagePage;
use Fisharebest\Webtrees\Http\RequestHandlers\MessageSelect;
use Fisharebest\Webtrees\Http\RequestHandlers\UserPage;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Module\ModuleInterface;
use Fisharebest\Webtrees\Registry;
use Fisharebest\Webtrees\Services\UserService;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\User;
use Illuminate\Support\Collection;

/**
 * @var int                    $block_id
 * @var string                 $context
 * @var ModuleInterface        $module
 * @var Tree                   $tree
 * @var Collection<int,object> $messages
 * @var Collection<int,User>   $users
 * @var UserService            $user_service
 */

?>

<?php if ($users->isNotEmpty()): ?>
    <div class="mb-3">
        <form method="post" action="<?= e(route(MessageSelect::class, ['tree' => $tree->name()])) ?>">
            <?= csrf_field() ?>
            <input type="hidden" name="url" value="<?= e(route(UserPage::class, ['tree' => $tree->name()])) ?>">
            <div class="row g-3 align-items-center">
                <div class="col-auto">
                    <label for="to"><?= I18N::translate('Send a message') ?></label>
                </div>
                <div class="col-auto">
                    <select class="form-control" id="to" name="to" required="required">
                        <option value=""><?= I18N::translate('&lt;select&gt;') ?></option>
                        <?php foreach ($users as $user): ?>
                            <option value="<?= e($user->userName()) ?>">
                                <?= e($user->realName()) ?> - <?= e($user->userName()) ?>
                            </option>
                        <?php endforeach ?>
                    </select>
                </div>
                <div class="col-auto">
                    <button type="submit" class="btn btn-primary"><?= I18N::translate('Send') ?></button>
                </div>
            </div>
        </form>
    </div>
<?php endif ?>

<form
    method="post"
    action="<?= e(route('module', ['action' => 'DeleteMessage', 'module' => $module->name(), 'context' => $context, 'tree' => $tree->name()])) ?>"
    data-wt-confirm="<?= I18N::translate('Are you sure you want to delete this message? It cannot be retrieved later.') ?>"
    onsubmit="return confirm(this.dataset.confirm);"
    id="messageform"
    name="messageform"
>
    <?= csrf_field() ?>
    <?php $scrollable_class = count($messages) > 10 ? ' jc-scrollable-table' : '' ?>
    <?php if ($messages->isNotEmpty()): ?>
        <div class="table-responsive mb-3">
            <table class="table-sm w-100<?= $scrollable_class ?>">
                <thead>
                    <tr>
                        <th class="wt-page-options-label text-center jc-column-1">
                            <?= I18N::translate('Delete') ?>
                            <a href="#"
                            onclick="$('#block-<?= $block_id ?> :checkbox').prop('checked', true); return false;">
                                <?= I18N::translate('All') ?>
                            </a>
                        </th>
                        <th class="wt-page-options-label jc-column-2"><?= I18N::translate('Subject') ?></th>
                        <th class="wt-page-options-label jc-column-3"><?= I18N::translate('Date sent') ?></th>
                        <th class="wt-page-options-label jc-column-4"><?= I18N::translate('Email address') ?></th>
                    </tr>
                </thead>

                <tbody>
                <?php foreach ($messages as $index => $message): ?>
                    <tr class="<?= 0 == $index % 2 ? 'bg-body' : 'bg-secondary' ?>">
                        <td class="wt-page-options-value text-center jc-column-1">
                            <input type="checkbox" name="message_id[]" value="<?= $message->message_id ?>" id="cb_message<?= $message->message_id ?>">
                        </td>

                        <td class="wt-page-options-value jc-column-2">
                            <a href="#message<?= $message->message_id ?>" data-bs-toggle="collapse" role="button"
                            aria-expanded="false" aria-controls="message<?= $message->message_id ?>">
                                <?= view('icons/expand') ?>
                                <?= view('icons/collapse') ?>
                                <b dir="auto"><?= e($message->subject) ?></b>
                            </a>
                        </td>

                        <td class="wt-page-options-value jc-column-3">
                            <?= view('components/datetime', ['timestamp' => $message->created]) ?>
                        </td>

                        <td class="wt-page-options-value jc-column-4">
                            <?php $user = $user_service->findByIdentifier($message->sender) ?>

                            <?php if ($user instanceof User): ?>
                                <bdi><?= e($user->realName()) ?></bdi> - <bdi><?= $user->email() ?></bdi>
                            <?php else: ?>
                                <a href="mailto:<?= e($message->sender) ?>"><?= e($message->sender) ?></a>
                            <?php endif ?>
                        </td>
                    </tr>

                    <tr>
                        <td class="wt-page-options-value" colspan="4">
                            <div id="message<?= $message->message_id ?>" class="collapse">
                                <div dir="auto" style="white-space: pre-wrap;">
                                    <?= Registry::markdownFactory()->autolink($message->body) ?>
                                </div>
                                <br>

                                <?php
                                /* I18N: When replying to an email, the subject becomes “RE: subject” */
                                if (!str_starts_with($message->subject, I18N::translate('RE: '))) {
                                    $message->subject = I18N::translate('RE: ') . $message->subject;
                                }

                                // If this user still exists, show a reply link.
                                if ($user instanceof User) {
                                    $reply_url = route(MessagePage::class, [
                                        'subject' => $message->subject,
                                        'to'      => $user->userName(),
                                        'tree'    => $tree->name(),
                                        'url'     => route(UserPage::class, ['tree' => $tree->name()]),
                                    ]);
                                    ?>

                                    <a class="btn btn-primary" href="<?= e($reply_url) ?>"
                                    title="<?= I18N::translate('Reply') ?>">
                                        <?= I18N::translate('Reply') ?>
                                    </a>
                                <?php } ?>
                                <button type="button" class="btn btn-danger"
                                        data-wt-confirm="<?= I18N::translate('Are you sure you want to delete this message? It cannot be retrieved later.') ?>"
                                        onclick="if (confirm(this.dataset.confirm)) {$('#messageform :checkbox').prop('checked', false); $('#cb_message<?= $message->message_id ?>').prop('checked', true); document.messageform.submit();}">
                                    <?= I18N::translate('Delete') ?>
                                </button>
                            </div>
                        </td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </div>
        <p>
            <button type="submit" class="btn btn-danger"><?= I18N::translate('Delete selected messages') ?></button>
        </p>
    <?php endif ?>
</form>
