<?php
/**
 * Change: datatable markup and styling.
 * Correction: removed (bool) from (bool) $tree->getPreference('SHOW_LAST_CHANGE') to show last change column
 * Functionallity: only show date in last change column. Do not show the time.
 * Themes: all themes *
 */
?>
<?php use Fisharebest\Webtrees\Database; ?>
<?php use Fisharebest\Webtrees\Functions\FunctionsDate ?>
<?php use Fisharebest\Webtrees\I18N; ?>
<?php use Fisharebest\Webtrees\Theme; ?>

<?php
// Count the number of linked records. These numbers include private records.
// It is not good to bypass privacy, but many servers do not have the resources
// to process privacy for every record in the tree
$count_sources = Database::prepare(
"SELECT l_to, COUNT(*) FROM `##sources` JOIN `##link` ON l_from = s_id AND l_file = s_file AND l_type = 'REPO' AND l_file = :tree_id GROUP BY l_to"
)->execute(['tree_id' => $tree->id()])->fetchAssoc();
?>

<table
    class="table table-bordered table-sm datatables d-none"
    data-dom="<?=  Theme::theme()->datatableMarkup() ?>"
    data-columns="<?= e(json_encode([
        null,
        ['visible' => array_sum($count_sources) > 0],
        ['visible' => $tree->getPreference('SHOW_LAST_CHANGE'), 'searchable' => false],
    ])) ?>"
    data-state-save="true"
    data-auto-width="false"
>
    <caption class="sr-only">
        <?= $caption ?? I18N::translate('Repositories') ?>
    </caption>

    <thead>
        <tr>
            <th><?= I18N::translate('Repository name') ?></th>
            <th><?= I18N::translate('Sources') ?></th>
            <th><?= I18N::translate('Last change') ?></th>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($repositories as $repository): ?>
            <tr class="<?= $repository->isPendingDeletion() ? 'old' : ($repository->isPendingAddition() ? 'new' : '') ?>">
                <!-- Repository name -->
                <td data-sort="<?= e($repository->getSortName()) ?>">
                    <a href="<?= e($repository->url()) ?>">
                        <?= $repository->getFullName() ?>
                    </a>
                </td>

                <!-- Count of linked sources -->
                <td class="center" data-sort="<?= $count_sources[$repository->xref()] ?? 0 ?>">
                    <?= I18N::number($count_sources[$repository->xref()] ?? 0) ?>
                </td>

                <!-- Last change -->
                <td data-sort="<?= $repository->lastChangeTimestamp(true) ?>">
                    <?= FunctionsDate::timestampToGedcomDate($repository->lastChangeTimestamp(true))->display() ?>
                </td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>
