<?php

use Fisharebest\Webtrees\I18N;

?>

<h2 class="wt-page-title"><?= $title ?></h2>

<table class="faq table table-sm">
    <?php foreach ($faqs as $id => $faq) : ?>
    <tr>
        <td p-1>
            <a href="#faq<?= e($id) ?>"><?= e($faq->header) ?></a>
        </td>
    </tr>
    <?php endforeach ?>
</table>

<?php foreach ($faqs as $id => $faq) : ?>
    <hr>
    <div class="row">
        <div class="faq_title col-sm-9 h3" id="faq<?= $id ?>">
            <?= e($faq->header) ?>       
        </div>
        <div class="faq_top font-italic col-sm-3 text-right">
            <a href="#content"><?= I18N::translate('back to top') ?></a>
        </div>
    </div>
    <div class="faq_body">
        <?= substr($faq->faqbody, 0, 1) === '<' ? $faq->faqbody : nl2br(e($faq->faqbody), false) ?>
    </div>
<?php endforeach ?>
