<?php

/* Prevent conflicts with webtrees icons in the control panel */

use Psr\Http\Message\ServerRequestInterface;
use Fisharebest\Webtrees\Registry;

$route = Registry::container()->get(ServerRequestInterface::class)->getAttribute('route');

?>

<?php if ($route->pathPrefix === '/admin'): ?>
    <?= view('::icons/individual') ?>
<?php else: ?>
    <span class="wt-icon-individual"><i class="fa-solid fa-user fa-fw" aria-hidden="true"></i></span>
<?php endif ?>
