<?php

/* Prevent conflicts with webtrees icons in the control panel */

use Psr\Http\Message\ServerRequestInterface;

$route = app(ServerRequestInterface::class)->getAttribute('route');

?>

<?php if ($route->pathPrefix === '/admin'): ?>
    <?= view('::icons/individual') ?>
<?php else: ?>
    <span class="wt-icon-individual"><i class="fa-solid fa-user fa-fw" aria-hidden="true"></i></span>
<?php endif ?>
